from fpdf import FPDF

class ReportPDF(FPDF):
    def footer(self):
        # Position 15 mm from bottom
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(128, 128, 128)  # Gray
        self.cell(
            0,
            6,
            "Generated by Cerevia Inc./ Cardio-Tool - For Research & Education Only",
            align="C"
        )

def create_pdf_report(data, title="Cardio-Tool"):
    """
    Generate a PDF report from a dictionary of data.
    Returns PDF as bytes (Latin-1 safe).

    Args:
        data (dict): Sections and their contents
        title (str): Title to display at the top of the report
    """
    pdf = ReportPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font("Arial", "B", 16)

    # Title (dynamic)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(
        0,
        10,
        f"{title} Report (Research Use Only)",
        ln=True,
        align="C",
        fill=True
    )
    pdf.ln(10)

    # Body
    pdf.set_font("Arial", "B", 12)
    pdf.set_text_color(0, 0, 139)  # Dark blue

    for section, content in data.items():
        # Section header
        pdf.cell(0, 8, f"{section}:", ln=True)
        pdf.set_font("Arial", "", 12)
        pdf.set_text_color(0, 0, 0)  # Black

        if isinstance(content, list):
            for item in content:
                pdf.cell(10)  # Indent
                pdf.cell(0, 6, f"- {item}", ln=True)
        else:
            pdf.cell(10)  # Indent
            pdf.cell(0, 6, str(content), ln=True)

        pdf.ln(4)
        pdf.set_font("Arial", "B", 12)
        pdf.set_text_color(0, 0, 139)

    # ✅ Return as bytes (encode Latin-1)
    return pdf.output(dest="S").encode("latin-1")
